# Generated by Django 3.2 on 2024-08-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20231121_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_phone_number',
        ),
    ]
