# Generated by Django 3.2 on 2023-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
